### ISSUE TITLE
Avoid page refresh upon opening a new tab for new day's message.

### ISSUE THREAD

**Issue by mereba** [kasahorowFoundation/chrome#23]
Each day, when I open a new tab, I expect to see the sentence for the day immediately. However, I always need to refresh the new tab before the fresh sentence for the day shows up. Kindly fix.

**Comment by mereba** [comment]
I have more information that might help.
I observed that this happens when the Internet connection is unreliable. I suggest that a buffer of say 5 days' worth of messages is fetched and saved locally in the browser, so that each day that day's message is fetched directly from the browser and displayed. Only when there are no messages for that day should the extension try to fetch the message from the Internet.

**Comment by kasahorow** [comment]
Should be fixed in version 2015.7.25
